flowchart LR
%% generated in 0.00s
    subgraph ai_gateway__feedback_loop
        ai_gateway__feedback_loop__FeedbackLoop____init__["__init__"]
        ai_gateway__feedback_loop__create_feedback_loop["create_feedback_loop"]
    end
    subgraph ai_gateway__gateway
        ai_gateway__gateway__suggest_improvements["suggest_improvements"]
        ai_gateway__gateway__GatewayConfig____post_init__["__post_init__"]
        ai_gateway__gateway__complete["complete"]
        ai_gateway__gateway__get_gateway["get_gateway"]
    end
    subgraph cli__main
        cli__main__CLI__cmd_new["cmd_new"]
        cli__main__CLI__cmd_execute["cmd_execute"]
        cli__main__CLI__cmd_ai_health["cmd_ai_health"]
        cli__main__CLI__cmd_ai_chat["cmd_ai_chat"]
        cli__main__CLI__cmd_ai_apply["cmd_ai_apply"]
        cli__main__CLI__cmd_ai_suggest["cmd_ai_suggest"]
        cli__main__CLI__cmd_load["cmd_load"]
        cli__main__CLI__cmd_models["cmd_models"]
        cli__main__CLI__cmd_parse["cmd_parse"]
        cli__main__CLI__cmd_plan["cmd_plan"]
    end
    subgraph config
        config__load_dotenv["load_dotenv"]
        config__reload_config["reload_config"]
        config__get_config["get_config"]
    end
    subgraph dsl__schema
        dsl__schema__get_system_prompt["get_system_prompt"]
        dsl__schema__get_json_schema["get_json_schema"]
        dsl__schema__validate_yaml_document["validate_yaml_document"]
    end
    subgraph examples___scripts
        examples___scripts__intent_to_openapi___slug["_slug"]
        examples___scripts__intent_to_intract__main["main"]
        examples___scripts__verify_expectations___parse_actions["_parse_actions"]
        examples___scripts__annotate_intract__main["main"]
        examples___scripts__intent_to_openapi__intent_to_openapi["intent_to_openapi"]
        examples___scripts__verify_expectations__main["main"]
        examples___scripts__verify_expectations___load_yaml["_load_yaml"]
        examples___scripts__annotate_intract__annotate_express["annotate_express"]
        examples___scripts__annotate_intract___slug["_slug"]
        examples___scripts__annotate_intract___actions["_actions"]
        examples___scripts__annotate_intract__annotate_python["annotate_python"]
        examples___scripts__intent_to_testql__main["main"]
        examples___scripts__annotate_intract___comment["_comment"]
        examples___scripts__intent_to_openapi__main["main"]
        examples___scripts__verify_expectations__verify["verify"]
    end
    subgraph executor__runner
        executor__runner__Executor____init__["__init__"]
        executor__runner__execute_intent["execute_intent"]
    end
    subgraph generator__contract_verify
        generator__contract_verify__verify_contract["verify_contract"]
        generator__contract_verify__write_contract_artifacts["write_contract_artifacts"]
    end
    subgraph generator__expectations
        generator__expectations__load_and_check_expectations["load_and_check_expectations"]
        generator__expectations__check_expectations["check_expectations"]
    end
    subgraph generator__intent_generator
        generator__intent_generator__extract_yaml_from_llm["extract_yaml_from_llm"]
        generator__intent_generator__IntentGenerator____init__["__init__"]
        generator__intent_generator___build_user_prompt["_build_user_prompt"]
        generator__intent_generator__IntentGenerator__generate["generate"]
    end
    subgraph generator__intract_manifest
        generator__intract_manifest__parse_api_actions["parse_api_actions"]
        generator__intract_manifest__intent_to_intract_dict["intent_to_intract_dict"]
        generator__intract_manifest___slug["_slug"]
        generator__intract_manifest__build_intract_manifest["build_intract_manifest"]
        generator__intract_manifest___safe_id["_safe_id"]
        generator__intract_manifest__write_intract_manifest["write_intract_manifest"]
    end
    subgraph generator__pipeline
        generator__pipeline___finalize["_finalize"]
        generator__pipeline___write_plan_artifacts["_write_plan_artifacts"]
        generator__pipeline__run_pipeline["run_pipeline"]
        generator__pipeline___container_logs["_container_logs"]
    end
    subgraph generator__session
        generator__session__write_session_artifacts["write_session_artifacts"]
    end
    subgraph generator__testql_scenario
        generator__testql_scenario___probe_path["_probe_path"]
        generator__testql_scenario__build_testql_scenario["build_testql_scenario"]
        generator__testql_scenario__write_testql_scenario["write_testql_scenario"]
    end
    subgraph parser__dsl_parser
        parser__dsl_parser__parse_dsl_file["parse_dsl_file"]
        parser__dsl_parser__parse_dsl["parse_dsl"]
    end
    subgraph planner__simulator
        planner__simulator___endpoint_to_func_name["_endpoint_to_func_name"]
        planner__simulator__plan_intent["plan_intent"]
        planner__simulator__Planner___generate_flask_code["_generate_flask_code"]
        planner__simulator__Planner___generate_fastapi_code["_generate_fastapi_code"]
    end
    subgraph sdk__client
        sdk__client__IterunClient__parse["parse"]
        sdk__client__IterunClient__validate["validate"]
        sdk__client__IterunClient__generate_and_run["generate_and_run"]
        sdk__client__IterunClient__schema["schema"]
    end
    subgraph web__app
        web__app__ai_complete["ai_complete"]
        web__app__get_schema["get_schema"]
        web__app__validate_yaml["validate_yaml"]
        web__app__generate_and_run_api["generate_and_run_api"]
        web__app__validate_intent["validate_intent"]
        web__app__ai_chat["ai_chat"]
        web__app__plan["plan"]
        web__app__generate_code["generate_code"]
        web__app__parse_intent["parse_intent"]
        web__app__execute["execute"]
        web__app__ai_apply_suggestions["ai_apply_suggestions"]
        web__app__ai_status["ai_status"]
        web__app__list_models["list_models"]
        web__app__ai_suggest["ai_suggest"]
    end
    config__reload_config --> config__load_dotenv
    generator__expectations__check_expectations --> generator__intract_manifest__parse_api_actions
    generator__expectations__load_and_check_expectations --> generator__expectations__check_expectations
    generator__intent_generator__IntentGenerator____init__ --> dsl__schema__get_system_prompt
    generator__intent_generator__IntentGenerator____init__ --> ai_gateway__gateway__get_gateway
    generator__intent_generator__IntentGenerator__generate --> generator__intent_generator___build_user_prompt
    generator__intent_generator__IntentGenerator__generate --> generator__intent_generator__extract_yaml_from_llm
    generator__intent_generator__IntentGenerator__generate --> dsl__schema__validate_yaml_document
    generator__testql_scenario__build_testql_scenario --> generator__intract_manifest__parse_api_actions
    generator__testql_scenario__build_testql_scenario --> generator__testql_scenario___probe_path
    generator__testql_scenario__write_testql_scenario --> generator__testql_scenario__build_testql_scenario
    generator__pipeline___write_plan_artifacts --> generator__intract_manifest__write_intract_manifest
    generator__pipeline___write_plan_artifacts --> generator__testql_scenario__write_testql_scenario
    generator__pipeline___finalize --> generator__pipeline___container_logs
    generator__pipeline___finalize --> generator__session__write_session_artifacts
    generator__pipeline__run_pipeline --> generator__pipeline___finalize
    generator__pipeline__run_pipeline --> planner__simulator__plan_intent
    generator__intract_manifest__build_intract_manifest --> generator__intract_manifest___safe_id
    generator__intract_manifest__build_intract_manifest --> generator__intract_manifest__parse_api_actions
    generator__intract_manifest__build_intract_manifest --> generator__intract_manifest___slug
    generator__intract_manifest__intent_to_intract_dict --> generator__intract_manifest__build_intract_manifest
    generator__intract_manifest__write_intract_manifest --> generator__intract_manifest__intent_to_intract_dict
    generator__contract_verify__write_contract_artifacts --> generator__intract_manifest__write_intract_manifest
    generator__contract_verify__write_contract_artifacts --> generator__testql_scenario__write_testql_scenario
    generator__contract_verify__verify_contract --> generator__contract_verify__write_contract_artifacts
    generator__contract_verify__verify_contract --> generator__intract_manifest__parse_api_actions
    generator__contract_verify__verify_contract --> generator__expectations__load_and_check_expectations
    examples___scripts__verify_expectations__verify --> examples___scripts__verify_expectations___load_yaml
    examples___scripts__verify_expectations__verify --> examples___scripts__verify_expectations___parse_actions
    examples___scripts__verify_expectations__main --> examples___scripts__verify_expectations__verify
    examples___scripts__annotate_intract___comment --> examples___scripts__annotate_intract___slug
    examples___scripts__annotate_intract__annotate_python --> examples___scripts__annotate_intract___actions
    examples___scripts__annotate_intract__annotate_express --> examples___scripts__annotate_intract___actions
    examples___scripts__annotate_intract__main --> examples___scripts__annotate_intract__annotate_python
    examples___scripts__annotate_intract__main --> examples___scripts__annotate_intract__annotate_express
    examples___scripts__intent_to_testql__main --> generator__testql_scenario__write_testql_scenario
    examples___scripts__intent_to_intract__main --> generator__intract_manifest__write_intract_manifest
    examples___scripts__intent_to_openapi__intent_to_openapi --> examples___scripts__intent_to_openapi___slug
    examples___scripts__intent_to_openapi__main --> examples___scripts__intent_to_openapi__intent_to_openapi
    planner__simulator__Planner___generate_fastapi_code --> planner__simulator___endpoint_to_func_name
    planner__simulator__Planner___generate_flask_code --> planner__simulator___endpoint_to_func_name
    web__app__get_schema --> dsl__schema__get_json_schema
    web__app__validate_yaml --> dsl__schema__validate_yaml_document
    web__app__generate_and_run_api --> generator__pipeline__run_pipeline
    web__app__parse_intent --> parser__dsl_parser__parse_dsl
    web__app__plan --> planner__simulator__plan_intent
    web__app__execute --> executor__runner__execute_intent
    web__app__validate_intent --> config__get_config
    web__app__ai_status --> ai_gateway__gateway__get_gateway
    web__app__list_models --> ai_gateway__gateway__get_gateway
    web__app__ai_complete --> ai_gateway__gateway__get_gateway
    web__app__ai_chat --> ai_gateway__gateway__get_gateway
    web__app__ai_suggest --> ai_gateway__feedback_loop__create_feedback_loop
    web__app__ai_apply_suggestions --> ai_gateway__feedback_loop__create_feedback_loop
    web__app__generate_code --> ai_gateway__gateway__get_gateway
    ai_gateway__gateway__GatewayConfig____post_init__ --> config__get_config
    ai_gateway__gateway__complete --> ai_gateway__gateway__get_gateway
    ai_gateway__gateway__suggest_improvements --> ai_gateway__gateway__get_gateway
    ai_gateway__feedback_loop__FeedbackLoop____init__ --> ai_gateway__gateway__get_gateway
    cli__main__CLI__cmd_new --> parser__dsl_parser__parse_dsl
    cli__main__CLI__cmd_load --> parser__dsl_parser__parse_dsl_file
    cli__main__CLI__cmd_parse --> parser__dsl_parser__parse_dsl
    cli__main__CLI__cmd_plan --> planner__simulator__plan_intent
    cli__main__CLI__cmd_execute --> executor__runner__execute_intent
    cli__main__CLI__cmd_execute --> config__get_config
    cli__main__CLI__cmd_ai_suggest --> ai_gateway__feedback_loop__create_feedback_loop
    cli__main__CLI__cmd_ai_apply --> ai_gateway__feedback_loop__create_feedback_loop
    cli__main__CLI__cmd_ai_chat --> ai_gateway__gateway__get_gateway
    cli__main__CLI__cmd_models --> ai_gateway__gateway__get_gateway
    cli__main__CLI__cmd_ai_health --> ai_gateway__gateway__get_gateway
    executor__runner__Executor____init__ --> config__get_config
    dsl__schema__validate_yaml_document --> parser__dsl_parser__parse_dsl
    dsl__schema__get_system_prompt --> dsl__schema__get_json_schema
    sdk__client__IterunClient__schema --> dsl__schema__get_json_schema
    sdk__client__IterunClient__validate --> dsl__schema__validate_yaml_document
    sdk__client__IterunClient__generate_and_run --> generator__pipeline__run_pipeline
    sdk__client__IterunClient__parse --> parser__dsl_parser__parse_dsl
