flowchart TD
%% generated in 0.00s
    ai_gateway__feedback_loop["ai_gateway.feedback_loop<br/>14 funcs"]
    ai_gateway__gateway["ai_gateway.gateway<br/>20 funcs"]
    cli__main["cli.main<br/>25 funcs"]
    config["config<br/>8 funcs"]
    dsl__schema["dsl.schema<br/>5 funcs"]
    examples___scripts["examples._scripts<br/>16 funcs"]
    executor__runner["executor.runner<br/>21 funcs"]
    generator__contract_verify["generator.contract_verify<br/>10 funcs"]
    generator__expectations["generator.expectations<br/>4 funcs"]
    generator__intent_generator["generator.intent_generator<br/>7 funcs"]
    generator__intract_manifest["generator.intract_manifest<br/>6 funcs"]
    generator__pipeline["generator.pipeline<br/>7 funcs"]
    generator__session["generator.session<br/>1 funcs"]
    generator__testql_scenario["generator.testql_scenario<br/>4 funcs"]
    parser__dsl_parser["parser.dsl_parser<br/>13 funcs"]
    planner__simulator["planner.simulator<br/>17 funcs"]
    sdk__client["sdk.client<br/>8 funcs"]
    web__app["web.app<br/>25 funcs"]
    web__app ==>|5| ai_gateway__gateway
    cli__main ==>|4| ai_gateway__gateway
    cli__main -->|3| parser__dsl_parser
    generator__contract_verify -->|3| generator__intract_manifest
    generator__intent_generator -->|2| dsl__schema
    generator__pipeline -->|2| executor__runner
    web__app -->|2| dsl__schema
    web__app -->|2| ai_gateway__feedback_loop
    cli__main -->|2| config
    cli__main -->|2| ai_gateway__feedback_loop
    cli__main -->|2| dsl__schema
    executor__runner -->|2| config
    sdk__client -->|2| dsl__schema
    generator__expectations -->|1| generator__intract_manifest
    generator__intent_generator -->|1| ai_gateway__gateway
    generator__intent_generator -->|1| parser__dsl_parser
    generator__testql_scenario -->|1| generator__intract_manifest
    generator__pipeline -->|1| generator__intract_manifest
    generator__pipeline -->|1| generator__testql_scenario
    generator__pipeline -->|1| generator__session
    generator__pipeline -->|1| planner__simulator
    generator__pipeline -->|1| generator__contract_verify
    examples___scripts -->|1| generator__testql_scenario
    examples___scripts -->|1| generator__intract_manifest
    web__app -->|1| generator__pipeline
    web__app -->|1| parser__dsl_parser
    web__app -->|1| planner__simulator
    web__app -->|1| executor__runner
    web__app -->|1| config
    ai_gateway__gateway -->|1| config
    ai_gateway__feedback_loop -->|1| ai_gateway__gateway
    cli__main -->|1| planner__simulator
    cli__main -->|1| executor__runner
    cli__main -->|1| generator__pipeline
    cli__main -->|1| generator__intract_manifest
    cli__main -->|1| generator__testql_scenario
    dsl__schema -->|1| parser__dsl_parser
    sdk__client -->|1| generator__pipeline
    sdk__client -->|1| parser__dsl_parser
    generator__contract_verify -->|1| generator__testql_scenario
    generator__contract_verify -->|1| generator__expectations
